version: '3'

services:
  node:
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - nodenet
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - nodenet
    depends_on:
      - node

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    command: --innodb-use-native-aio=0
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
